---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: example-webapp
  namespace: example-ns
spec:
  url: oci://example-helm-path
  provider: azure
  interval: 5m
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-webapp
  namespace: example-ns
spec:
  releaseName: example-webapp
  chart:
    spec:
      chart: example-webapp
      version: ">=1"
      sourceRef:
        kind: HelmRepository
        name: example-webapp
        namespace: example-ns
  interval: 5m
  values:
    name: example-webapp
    namespace: example-ns
    public:
      fqdn: example-fqdn
    image:
      repository: example-repo
      name: example-webapp
      tag: example-tag